apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: iac-dal
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-11-25T20:03:50Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: iac-dal
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: iac-dal
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: iac-dal-0.1.0
  name: iac-dal
  namespace: default
  resourceVersion: "8202681"
  selfLink: /apis/apps/v1/namespaces/default/deployments/iac-dal
  uid: e7ab7c70-a0f2-4fb3-9eb8-a6a240856194
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: iac-dal
      app.kubernetes.io/name: iac-dal
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "20"
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: iac-dal
        app.kubernetes.io/name: iac-dal
    spec:
      containers:
      - args:
        - --
        - /entrypoint
        command:
        - /linkerd-await
        env:
        - name: ENV
          value: dev
        - name: DC
          value: dev-us1
        - name: AWS_REGION
          value: us-east-1
        - name: LOG_DEBUG
          value: "1"
        - name: AWS_S3_FORCE_PATH
          value: "true"
        - name: AWS_S3_ENDPOINT
          value: http://minio:4572
        - name: AWS_SNS_ENDPOINT
          value: http://sns-s12vsns:4575
        - name: AWS_SQS_ENDPOINT
          value: http://elasticmq:4576
        - name: AWS_SQS_MAX_CONSUMERS
          value: "1"
        - name: AWS_SECRETSMANAGER_ENDPOINT
          value: http://secretsmanager:4584
        - name: AWS_STS_ENDPOINT
          value: http://sts:4592
        - name: AWS_DYNAMO_ENDPOINT
          value: http://dynamodb-dynamodb-local:4569
        - name: AWS_SES_ENDPOINT
          value: http://ses:4579
        - name: GCP_TEST_API_KEY
          value: AIzaSyDpnctbDLpzS4_3DVqwrnljYBOln2ypH2E
        - name: GCP_TEST_ACCESS_TOKEN
          value: ya29.a0AfH6SMA_l2eCcb0n-khIhMkb774klJWNpJfWzJfUZ1dC7XvaEo8WNX5F7GGcF9jueVy1BhEFRGzo8bcniUxFoERTVmVm_H5iEZ7i7--Q7hn2tdC10aVVWFbOSQge-DvH0MKmT3rkaoFbDeWC-HScbFDjmsAWuU_tEvd0sfixq9w
        - name: GCP_TEST_REFRESH_TOKEN
          value: 1//03VU7NJqO6IuwCgYIARAAGAMSNwF-L9Ir1emttFSBoBtCAV9eIS0ANNJbU7vl17Mw5QTzK1RtYhVN10PWNuZnNTE3YCB_FWeyDAA
        - name: AZURE_CLIENT_ID
          value: f9194fed-96ef-4927-ad0f-8572315b540c
        - name: AZURE_TENANT_ID
          value: 18360841-3f87-44a6-8c9a-3ffc680611a0
        - name: AZURE_CLIENT_SECRET
          value: SSjtY.0s3OcsyoRAM9~luR1x5.rZkl_hxl
        - name: CONFIG_SDK_KEY
          valueFrom:
            secretKeyRef:
              key: sdkkey
              name: launchdarkly-creds
        - name: REACT_APP_LAUNCH_DARKLY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: clientsideid
              name: launchdarkly-creds
        - name: AWS_ACCESS_KEY_ID
          value: AKIATLBK6KEBPFS75YET
        - name: AWS_SECRET_ACCESS_KEY
          value: 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
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: DD_ENV
          value: dev
        - name: DD_SERVICE
          value: iac-dal
        - name: DD_VERSION
          value: latest
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: GRPC_ENDPOINT_ARCHITECTURE_MANAGER
          value: architecture-manager:3000
        - name: GRPC_ENDPOINT_AUDIT_DAL
          value: audit-dal:3000
        - name: GRPC_ENDPOINT_AUTH
          value: auth:3000
        - name: GRPC_ENDPOINT_BENCHMARK_DAL
          value: benchmark-dal:3000
        - name: GRPC_ENDPOINT_CHANGESET_DAL
          value: changeset-dal:3000
        - name: GRPC_ENDPOINT_CI_DAL
          value: ci-dal:3000
        - name: GRPC_ENDPOINT_CLOUDPLATFORM_DAL
          value: cloudplatform-dal:3000
        - name: GRPC_ENDPOINT_CONNECTOR_DAL
          value: connector-dal:3000
        - name: GRPC_ENDPOINT_DISKANALYZER_COORDINATOR
          value: diskanalyzer-coordinator-headless:3000
        - name: GRPC_ENDPOINT_DISKANALYZER_PROVISIONER
          value: diskanalyzer-provisioner:3000
        - name: GRPC_ENDPOINT_FILEUPLOAD_DAL
          value: fileupload-dal:3000
        - name: GRPC_ENDPOINT_GRAPH_DAL
          value: graph-dal:3000
        - name: GRPC_ENDPOINT_IAC_DAL
          value: iac-dal:3000
        - name: GRPC_ENDPOINT_NOTIFICATION_DAL
          value: notification-dal:3000
        - name: GRPC_ENDPOINT_PACKAGEREGISTRY_DAL
          value: packageregistry-dal:3000
        - name: GRPC_ENDPOINT_PRODUCT_DAL
          value: product-dal:3000
        - name: GRPC_ENDPOINT_REPORT_DAL
          value: report-dal:3000
        - name: GRPC_ENDPOINT_SECRETS_DAL
          value: secrets-dal:3000
        - name: GRPC_ENDPOINT_SECURITYTOOL_DAL
          value: securitytool-dal:3000
        - name: GRPC_ENDPOINT_TECHSTACK_DAL
          value: techstack-dal:3000
        - name: GRPC_ENDPOINT_TENANT_DAL
          value: tenant-dal:3000
        - name: GRPC_ENDPOINT_USER_DAL
          value: user-dal:3000
        - name: GRPC_ENDPOINT_USERDIRECTORY_DAL
          value: userdirectory-dal:3000
        - name: GRPC_ENDPOINT_VERSIONCONTROL_DAL
          value: versioncontrol-dal:3000
        envFrom:
        - configMapRef:
            name: iac-dal
        image: beyond/iac-dal:latest
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                touch /tmp/preStopCalled && /bin/sleep 20
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /live
            port: 7357
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: iac-dal
        ports:
        - containerPort: 3000
          name: grpc
          protocol: TCP
        - containerPort: 6161
          name: metrics
          protocol: TCP
        - containerPort: 10000
          name: gql
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 7357
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 4G
          requests:
            cpu: 10m
            memory: 64M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/secrets
          name: secrets
          readOnly: true
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - -url=jdbc:postgresql://postgres:5432/pgdev?sslmode=disable
        - -user=$(POSTGRES_USERNAME)
        - -password=$(POSTGRES_PASSWORD)
        - -schemas=iac
        - migrate
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-creds
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: postgres-creds
        image: beyond/iac-dal-migrator:latest
        imagePullPolicy: IfNotPresent
        name: iac-dal-migrator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secrets
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: sdkkey
                path: CONFIG_SDK_KEY
              name: launchdarkly-creds
          - secret:
              items:
              - key: clientsideid
                path: REACT_APP_LAUNCH_DARKLY_CLIENT_ID
              name: launchdarkly-creds
          - secret:
              items:
              - key: password
                path: POSTGRES_PASSWORD
              name: postgres-creds
          - secret:
              items:
              - key: username
                path: POSTGRES_USER
              name: postgres-creds
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-11-25T20:04:02Z"
    lastUpdateTime: "2020-11-25T20:04:02Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-11-25T20:03:50Z"
    lastUpdateTime: "2020-11-25T20:04:02Z"
    message: ReplicaSet "iac-dal-66cdfb54fc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
